### ISSUE TITLE
[Network] addFriendScreen api 연결

### ISSUE THREAD

**Issue by seoy-54** [APPS-sookmyung/2024-OUTFOOT-client#35]
## 🛠 Issue

add_friend_screen UI API 연결

## 📝 To-do

- [ ] 친구 추가 성공
- [ ] 친구 추가 실패(존재하지 않는 회원)
- [ ] 친구 추가 실패(이미 존재하는 친구)
- [ ] 친구 추가 실패(자기 자신 추가 불가)
- [ ] 스크린 연결
