### ISSUE TITLE
[Network] profileMyPage API 연결

### ISSUE THREAD

**Issue by seoy-54** [APPS-sookmyung/2024-OUTFOOT-client#36]
## 🛠 Issue

profileMyPage API 연결

## 📝 To-do

- [x] 내 정보 조회
- [ ] 도장판 전체 조회
- [x] 내 정보 조회 스크린 연결
- [ ] 도장판 전체 조회 스크린 연결
