### ISSUE TITLE
[Network] upload API 연결

### ISSUE THREAD

**Issue by lhaerim** [APPS-sookmyung/2024-OUTFOOT-client#37]
## 📝 To-do

- [x] 인증판 추가 (생성)
- [ ] 도장판 개별 조회 활용
- [x] 사진 필수 선택 
- [x] 스크린과 연결
