### ISSUE TITLE
[Chore] 반응형 및 ui 수정

### ISSUE THREAD

**Issue by seoy-54** [APPS-sookmyung/2024-OUTFOOT-client#64]
## 🛠 Issue

반응형 및 ui 수정

## 📝 To-do

- [x] 반응형
- [x] make_personal_goal ui 수정
- [x] 도장 생성 일러스트 추가
- [x] checkpage_foot ui 수정
